Repository exercism/vimscript, pull requests merged in 2024-02, with the labels that each got.

#266 `pop-count`: rename to `eliuds-eggs`
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/example.vim
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/pop_count.vader
  exercises/practice/eliuds-eggs/pop_count.vim
Labels: x:size/tiny

#267 Update eliud's eggs files
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/eliuds_eggs.vader
  exercises/practice/eliuds-eggs/eliuds_eggs.vim
Labels: x:rep/tiny

#268 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#269 Set grains to WIP
  config.json
Labels: x:rep/tiny

#182 Update CI to run example.vim in isolation
  .github/workflows/ci.yml
  .github/workflows/test.yml
  bin/ci
  bin/verify-exercises
Labels: x:action/improve, x:type/ci

#270 Forego parallel-letter-frequency
  config.json
Labels: x:rep/tiny
