Repository exercism/vimscript, pull requests merged in 2024-04, with the labels that each got.

#281 scrabble-score: sync
  exercises/practice/scrabble-score/.docs/instructions.md
  exercises/practice/scrabble-score/.docs/introduction.md
Labels: x:size/tiny

#282 dnd-character: sync
  exercises/practice/dnd-character/.docs/instructions.md
  exercises/practice/dnd-character/.docs/introduction.md
Labels: x:size/tiny

#286 Sync atbash-cipher tests
  exercises/practice/atbash-cipher/atbash_cipher.vader
Labels: x:action/sync, x:rep/tiny

#287 Sync bob tests
  exercises/practice/bob/bob.vader
Labels: x:action/sync, x:rep/tiny

#289 Sync hamming tests
  exercises/practice/hamming/.meta/example.vim
  exercises/practice/hamming/hamming.vader
  exercises/practice/hamming/hamming.vim
Labels: x:action/sync, x:rep/tiny

#290 Sync leap tests
  exercises/practice/leap/leap.vader
Labels: x:action/sync, x:rep/tiny

#291 Sync phone number tests
  exercises/practice/phone-number/phone_number.vader
Labels: x:size/tiny, x:action/sync
