Repository exercism/vimscript, pull requests merged in 2024-03, with the labels that each got.

#272 Sync metadata
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/strain/.meta/config.json
Labels: x:action/sync, x:rep/tiny

#276 Add sieve-exercise
  config.json
  exercises/practice/sieve/.docs/instructions.md
  exercises/practice/sieve/.docs/introduction.md
  exercises/practice/sieve/.meta/config.json
  exercises/practice/sieve/.meta/example.vim
  exercises/practice/sieve/.meta/tests.toml
  exercises/practice/sieve/sieve.vader
  exercises/practice/sieve/sieve.vim
Labels: x:size/medium, x:module/practice-exercise

#280 two-fer: sync
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
Labels: x:size/tiny

#279 sieve: sync
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny
