Repository exercism/vimscript, pull requests merged in 2024-01, with the labels that each got.

#251 Update CI to Vim 9
  .github/workflows/ci.yml
Labels: x:type/ci, x:rep/small

#239 Add transpose
  config.json
  exercises/practice/transpose/.docs/instructions.md
  exercises/practice/transpose/.meta/config.json
  exercises/practice/transpose/.meta/example.vim
  exercises/practice/transpose/.meta/tests.toml
  exercises/practice/transpose/transpose.vader
  exercises/practice/transpose/transpose.vim
Labels: x:module/practice-exercise, x:rep/medium

#250 Update more tests
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/allergies.vader
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/anagram.vader
  exercises/practice/largest-series-product/.meta/example.vim
  exercises/practice/largest-series-product/.meta/tests.toml
  exercises/practice/largest-series-product/largest_series_product.vader
  exercises/practice/phone-number/.meta/tests.toml
  exercises/practice/phone-number/phone_number.vader
  exercises/practice/run-length-encoding/.meta/tests.toml
Labels: x:action/sync, x:rep/tiny

#255 Add approaches to `leap`
  exercises/practice/leap/.approaches/boolean-chain/content.md
  exercises/practice/leap/.approaches/boolean-chain/snippet.txt
  exercises/practice/leap/.approaches/config.json
  exercises/practice/leap/.approaches/if-else-statements/content.md
  exercises/practice/leap/.approaches/if-else-statements/snippet.txt
  exercises/practice/leap/.approaches/introduction.md
Labels: x:action/create, x:type/content

#260 Fix broken if-else approaches link
  exercises/practice/leap/.approaches/introduction.md
Labels: x:rep/tiny

#264 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
